(* This file was generated by the codegen in
   [lib/browser/codegen/types/browser_types_codegen.ml]. *)

open! Import

type binary_type = private Js.js_string Js.t
type css_numeric_base_type = private Js.js_string Js.t
type canvas_direction = private Js.js_string Js.t
type canvas_fill_rule = private Js.js_string Js.t
type canvas_font_kerning = private Js.js_string Js.t
type canvas_font_stretch = private Js.js_string Js.t
type canvas_font_variant_caps = private Js.js_string Js.t
type canvas_text_align = private Js.js_string Js.t
type canvas_text_baseline = private Js.js_string Js.t
type canvas_text_rendering = private Js.js_string Js.t
type color_space_conversion = private Js.js_string Js.t
type composite_operation = private Js.js_string Js.t
type document_ready_state = private Js.js_string Js.t
type end_of_stream_error = private Js.js_string Js.t
type ending_type = private Js.js_string Js.t
type fetch_priority = private Js.js_string Js.t
type fill_mode = private Js.js_string Js.t
type fullscreen_navigation_ui = private Js.js_string Js.t
type highlight_type = private Js.js_string Js.t
type image_orientation = private Js.js_string Js.t
type image_smoothing_quality = private Js.js_string Js.t
type navigation_commit_behavior = private Js.js_string Js.t
type navigation_focus_reset = private Js.js_string Js.t
type navigation_history_behavior = private Js.js_string Js.t
type navigation_scroll_behavior = private Js.js_string Js.t
type navigation_type = private Js.js_string Js.t
type playback_direction = private Js.js_string Js.t
type predefined_color_space = private Js.js_string Js.t
type premultiply_alpha = private Js.js_string Js.t
type readable_stream_reader_mode = private Js.js_string Js.t
type referrer_policy = private Js.js_string Js.t
type request_cache = private Js.js_string Js.t
type request_credentials = private Js.js_string Js.t
type request_destination = private Js.js_string Js.t
type request_duplex = private Js.js_string Js.t
type request_mode = private Js.js_string Js.t
type request_redirect = private Js.js_string Js.t
type resize_observer_box_options = private Js.js_string Js.t
type resize_quality = private Js.js_string Js.t
type response_type = private Js.js_string Js.t
type scroll_behavior = private Js.js_string Js.t
type scroll_logical_position = private Js.js_string Js.t
type scroll_restoration = private Js.js_string Js.t
type selection_mode = private Js.js_string Js.t
type shadow_root_mode = private Js.js_string Js.t
type slot_assignment_mode = private Js.js_string Js.t
type timeline_range = private Js.js_string Js.t
type visibility_state = private Js.js_string Js.t
type worker_type = private Js.js_string Js.t
type xml_http_request_response_type = private Js.js_string Js.t
